name: Using the DST FIST Cluster "Apollo"
description: This is a comprehensive guide to using the DST FIST Cluster "Apollo"
repository: JU-DS-Lab/quick-start
site_branch: master
timezone: Asia/Kolkata
plugins:
- jekyll-gfm-admonitions
- jekyll-optional-front-matter
